-- MySQL Script generated by MySQL Workbench
-- Wed Aug 18 10:28:55 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema AlquilerLibrosDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AlquilerLibrosDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AlquilerLibrosDB` DEFAULT CHARACTER SET utf8 ;
USE `AlquilerLibrosDB` ;

-- -----------------------------------------------------
-- Table `AlquilerLibrosDB`.`libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AlquilerLibrosDB`.`libro` (
  `id_lib` INT NOT NULL,
  `nombre_lib` VARCHAR(45) NOT NULL,
  `tipo_lib` VARCHAR(20) NOT NULL,
  `autor_lib` VARCHAR(30) NOT NULL,
  `isbn_lib` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_lib`),
  UNIQUE INDEX `libro_id_UNIQUE` (`id_lib` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AlquilerLibrosDB`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AlquilerLibrosDB`.`persona` (
  `dni_per` INT NOT NULL,
  `nombre_per` VARCHAR(35) NOT NULL,
  `apellido_per` VARCHAR(35) NOT NULL,
  `edad_per` INT NULL,
  PRIMARY KEY (`dni_per`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AlquilerLibrosDB`.`alquiler`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AlquilerLibrosDB`.`alquiler` (
  `id_alq` INT NOT NULL AUTO_INCREMENT,
  `fecha_prestamo` DATETIME NOT NULL,
  `fecha_devolucion` DATETIME NOT NULL,
  `persona_dni_per` INT NOT NULL,
  `libro_id_lib` INT NOT NULL,
  PRIMARY KEY (`id_alq`, `persona_dni_per`, `libro_id_lib`),
  INDEX `fk_alquiler_persona_idx` (`persona_dni_per` ASC) VISIBLE,
  INDEX `fk_alquiler_libro1_idx` (`libro_id_lib` ASC) VISIBLE,
  CONSTRAINT `fk_alquiler_persona`
    FOREIGN KEY (`persona_dni_per`)
    REFERENCES `AlquilerLibrosDB`.`persona` (`dni_per`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alquiler_libro1`
    FOREIGN KEY (`libro_id_lib`)
    REFERENCES `AlquilerLibrosDB`.`libro` (`id_lib`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
