-- MySQL Script generated by MySQL Workbench
-- Wed Aug 18 14:07:52 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema emple_dep
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema emple_dep
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `emple_dep` DEFAULT CHARACTER SET utf8 ;
USE `emple_dep` ;

-- -----------------------------------------------------
-- Table `emple_dep`.`departamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emple_dep`.`departamentos` (
  `id_dep` INT NOT NULL AUTO_INCREMENT,
  `nombre_dep` VARCHAR(25) NOT NULL,
  `direccion_dep` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_dep`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `emple_dep`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emple_dep`.`empleados` (
  `num_legajo` INT NOT NULL AUTO_INCREMENT,
  `dni_emp` INT NOT NULL,
  `apellido_emp` VARCHAR(20) NOT NULL,
  `nombre_emp` VARCHAR(20) NOT NULL,
  `fecha_nacimiento` DATETIME NOT NULL,
  `fecha_incorporacion` DATETIME NOT NULL,
  `cargo_emp` VARCHAR(25) NOT NULL,
  `sueldo_neto_emp` DOUBLE NOT NULL,
  `departamentos_id_dep` INT NOT NULL,
  PRIMARY KEY (`num_legajo`, `departamentos_id_dep`),
  INDEX `fk_empleados_departamentos_idx` (`departamentos_id_dep` ASC) VISIBLE,
  UNIQUE INDEX `num_legajo_UNIQUE` (`num_legajo` ASC) VISIBLE,
  UNIQUE INDEX `dni_emp_UNIQUE` (`dni_emp` ASC) VISIBLE,
  CONSTRAINT `fk_empleados_departamentos`
    FOREIGN KEY (`departamentos_id_dep`)
    REFERENCES `emple_dep`.`departamentos` (`id_dep`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
