spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: rootroot
    url: jdbc:mysql://localhost:3306/StudentsRaffle_db?useSSL=false&serverTimezone=UTC
    username: root
  jpa:
    properties:
      hibernate.format_sql: true
      use_sql_comments: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show_sql: true
    hibernate:
      ddl-auto: update