create table STUDENT (
                         ID INT,
                         FIRST_NAME VARCHAR(50),
                         LAST_NAME VARCHAR(50)
);
insert into STUDENT (ID, FIRST_NAME, LAST_NAME) values (1, 'Cosetta', 'Fedorchenko');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME) values (2, 'Dagmar', 'Dwerryhouse');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME) values (3, 'Ev', 'Charrington');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME) values (4, 'Geraldine', 'Wallwood');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME) values (5, 'Averell', 'Gorst');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME) values (6, 'Gina', 'Bohlje');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME) values (7, 'Helaine', 'Raynard');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME) values (8, 'Elianore', 'Braga');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME) values (9, 'Allen', 'Pape');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME) values (10, 'Salim', 'Cometti');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME) values (11, 'Barnard', 'Lodwig');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME) values (12, 'Margaux', 'Ivancevic');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME) values (13, 'Tabatha', 'Stendall');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME) values (14, 'Robinett', 'Hartman');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME) values (15, 'Cordy', 'Rase');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME) values (16, 'Jules', 'Mesias');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME) values (17, 'Lawton', 'Boykett');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME) values (18, 'Sula', 'Tather');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME) values (19, 'Tiffie', 'Winser');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME) values (20, 'Fremont', 'Chaffen');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME) values (21, 'Tadd', 'Bourdice');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME) values (22, 'Cacilie', 'Stallard');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME) values (23, 'Willetta', 'Gueinn');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME) values (24, 'Louisette', 'Dunnett');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME) values (25, 'Joann', 'Redmile');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME) values (26, 'Marylynne', 'Gilbard');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME) values (27, 'Kim', 'Ferber');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME) values (28, 'Raphaela', 'Gammie');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME) values (29, 'Leilah', 'Redgrave');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME) values (30, 'Liz', 'Ashworth');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME) values (31, 'Lynn', 'Ogelsby');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME) values (32, 'Bill', 'Drayton');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME) values (33, 'Artair', 'Callear');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME) values (34, 'Kym', 'Stedmond');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME) values (35, 'Rozalie', 'Bellefant');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME) values (36, 'Alane', 'Neumann');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME) values (37, 'Raul', 'Svanini');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME) values (38, 'Carmela', 'Arrundale');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME) values (39, 'Dyanne', 'Ahmad');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME) values (40, 'Brenden', 'De Roos');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME) values (41, 'Ainsley', 'Mc Caughan');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME) values (42, 'Augusta', 'Espley');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME) values (43, 'Cecilla', 'Ballaam');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME) values (44, 'Waldon', 'Revie');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME) values (45, 'Adamo', 'Stubbeley');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME) values (46, 'Cass', 'Topley');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME) values (47, 'Renae', 'Mully');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME) values (48, 'Noe', 'Sinyard');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME) values (49, 'Madelle', 'Bilfoot');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME) values (50, 'Erin', 'Durden');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME) values (51, 'Raychel', 'Nice');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME) values (52, 'Ree', 'Vispo');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME) values (53, 'Gardy', 'Sails');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME) values (54, 'Samantha', 'Murtimer');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME) values (55, 'Evangelia', 'Grist');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME) values (56, 'Laure', 'Robic');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME) values (57, 'Anneliese', 'MacAlister');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME) values (58, 'Miltie', 'Winpenny');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME) values (59, 'Dorise', 'Lillywhite');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME) values (60, 'Krystal', 'Linne');
